server:
  servlet:
    context-path: 
      /treeBucket
  tomcat:
    connection-timeout: 
      6000
    
    
spring:
  profiles:
    active: 
      dev
  application:
    name: 
      Tree-Bucket
  servlet:
    multipart:
      enabled: true
      max-file-size:
        6MB
      max-request-size:
        10MB
        